// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybgjdilxmazgonqtacrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZ2pkaWx4bWF6Z29ucXRhY3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Nzk2NzcsImV4cCI6MjA3MDE1NTY3N30.1fTVA8dyokvO8B8VDkLnxAkri5u4Kdm2uSptC66SglI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});